global:
  scrape_interval:  15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fortest'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'fortest'